/* ============================================================================================================
 * Damiano Tasso 944232
 *
 * Declaration of the Interrupt Service Routines generated by the Timer on TC and by the UART on byte received. 
 * ============================================================================================================
*/
#ifndef __SERVICE_ROUTINES_H__
    #define __SERVICE_ROUTINES_H__
    
    #include "cytypes.h"
    #include "global.h"
    #include "stdio.h"
    
    CY_ISR_PROTO(TIMER_ISR);
    
    CY_ISR_PROTO(UART_RX_ISR);
    
#endif
/* [] END OF FILE */
